# Copiez ce contenu dans Streamlit Cloud > Settings > Secrets pour ce projet.
# Ne mettez JAMAIS ce fichier une fois rempli sur GitHub.

APP_PASSWORD = "VotreMotDePasseAdminFortEtDifferentDOmniRecrut"

GEMINI_API_KEY = "VotreCleAPIGeminiIndependante"

EMAIL_USER = "votre.adresse@gmail.com"
EMAIL_PASSWORD = "votre_mot_de_passe_application"
EMAIL_IMAP = "imap.gmail.com"
