# Clé API pour l'Intelligence Artificielle
GEMINI_API_KEY = "AQ.Ab8RN6Iigpt2GpIypy7ViN43878WY5-zdnE2FmLrF7f8jPHHOg"

# Configuration de la boîte mail pour le sourcing automatique
EMAIL_USER = "stephanrolland@gmail.com"
EMAIL_PASSWORD = "npje dhxf ujkz qvrh"
EMAIL_IMAP = "imap.gmail.com"
APP_PASSWORD = "Yamsteph2212"